---
-
  hosts: localhost
  tasks:
    -
      shell: "echo \"labas\""
    -
      apt:
        become: true
        name: hostapd
        state: latest
      name: "Install hostapd"
    -
      lineinfile:
        become: true
        dest: /etc/dhcpcd.conf
        line: "denyinterfaces wlan0"
        regexp: "denyinterfaces wlan0"
    -
      blockinfile:
        become: true
        block: |
            iface wlan0 inet static
                address 10.10.0.1
                netmask 255.255.255.0
        dest: /etc/network/interfaces
    -
      service:
        become: true
        name: dhcpcd
        state: restarted
    -
      become: true
      command: "ifdown wlan0"
    -
      become: true
      command: "ifup wlan0"
    -
      copy:
        content: ""
        dest: /etc/hostapd/hostapd.conf
        force: false
        group: sys
        mode: 365
        owner: root
      name: "ensure file exists"
    -
      blockinfile:
        become: true
        block: "interface=wlan0\n\
            driver=nl80211\n\
            ssid=Elpis\n\
            channel=6\n\
            wmm_enabled=1\n\
            wpa=1\n\
            wpa_passphrase=projectelpis\n\
            wpa_key_mgmt=WPA-PSK\n\
            wpa_pairwise=TKIP\n\
            rsn_pairwise=CCMP\n\
            auth_algs=1\n\
            macaddr_acl=0   \n"
        dest: /etc/network/interfaces
    -
      copy:
        content: ""
        dest: /etc/init.d/elpis
        force: false
        group: sys
        mode: 365
        owner: root
      name: "ensure file exists"
    -
      blockinfile:
        become: true
        block: |
            #!/bin/sh
            hostapd -B /etc/hostapd/hostapd.conf
        dest: /etc/init.d/elpis
    -
      become: true
      command: "update-rc.d hostapd defaults"
    -
      become: true
      command: reboot
