---
- hosts: localhost
  tasks:
      - name: Install hostapd
        apt: name=hostapd state=latest
        become: true
      - lineinfile:
          dest: /etc/dhcpcd.conf
          regexp: 'denyinterfaces wlan0'
          line: 'denyinterfaces wlan0'
        become: true
      - copy:
          src: interfaces
          dest: /etc/network/interfaces
        become: true
      - service:
          name: dhcpcd
          state: restarted
        become: true
      - command: ifdown wlan0
        become: true
      - command: ifup wlan0
        become: true
      - name: ensure file exists
        copy:
          content: ""
          dest: /etc/hostapd/hostapd.conf
          force: no
          group: sys
          owner: root
          mode: 0555
      - blockinfile:
          dest: /etc/hostapd/hostapd.conf
          marker: ""
          block: |
            interface=wlan0
            driver=nl80211
            ssid=Elpis
            channel=6
            wmm_enabled=1
            wpa=1
            wpa_passphrase=projectelpis
            wpa_key_mgmt=WPA-PSK
            wpa_pairwise=TKIP
            rsn_pairwise=CCMP
            auth_algs=1
            macaddr_acl=0
        become: true
      - lineinfile:
            dest: /etc/default/hostapd
            regexp: 'DAEMON_CONF="/etc/hostapd/hostapd.conf"'
            line: 'DAEMON_CONF="/etc/hostapd/hostapd.conf"'
        become: true
      - lineinfile:
            dest: /etc/init.d/hostpad
            regexp: 'DAEMON_CONF='
            line: 'DAEMON_CONF=/etc/hostapd/hostapd.conf'
        become: true
      - command: update-rc.d /etc/init.d/hostapd defaults
        become: true
      - command: update-rc.d /etc/init.d/hostapd enable
        become: true
